[package]
name = "quickrandr"
version = "0.2.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
clap = "*"

# Unneeded as this should be small and fast
#
#edid = "*"
